export const LOGIN = "LOGIN"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const REGISTER = "REGISTER"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"

export const FETCH_CONTACT = "FETCH_CONTACT"
export const FETCH_CONTACT_SUCCESSFUL = "FETCH_CONTACT_SUCCESSFUL"
export const FETCH_CONTACT_FAILED = "FETCH_CONTACT_FAILED"


export const ADD_CONTACT = "ADD_CONTACT"
export const ADD_CONTACT_SUCCESSFUL = "ADD_CONTACT_SUCCESSFUL"
export const ADD_CONTACT_FAILED = "ADD_CONTACT_FAILED"


export const UPDATE_CONTACT = "UPDATE_CONTACT"
export const UPDATE_CONTACT_SUCCESSFUL = "UPDATE_CONTACT_SUCCESSFUL"
export const UPDATE_CONTACT_FAILED = "UPDATE_CONTACT_FAILED"


export const DELETE_CONTACT = "DELETE_CONTACT"
export const DELETE_CONTACT_SUCCESSFUL = "DELETE_CONTACT_SUCCESSFUL"
export const DELETE_CONTACT_FAILED = "DELETE_CONTACT_FAILED"